Update of the abbreviations
koenderks/jfa pull request #206
Opened 2024-12-16 13:19 UTC by federicapicogna

2024-12-16 13:31 UTC, koenderks requested changes
1. Didn't we settle on negative predictive rate parity? Why the change **back** to negative predictive value? I think you might not have reset your development branch after merging your previous pull request.
2. What happens when you use `metric = "eo"` in `model_fairness()`. It should at least give a warning message or something that it is not possible.
3. Can you make sure that the unit tests work again.
4. Change "dp" back to "pp" since the proportional parity is equivalent to the disparate impact. "dp" is demographic parity and is calculated as (TP + FP)

2024-12-17 14:34 UTC, koenderks commented
Unit tests still fail:

```
Failure ('test-fairness-selection.R:25:3'): Validation of fairness selection ──
outcome$measure not equal to "dp".
1/1 mismatches
x[1]: "eo"
y[1]: "dp"
```

2024-12-18 11:15 UTC, koenderks requested changes
Check the unit tests

2025-01-03 17:37 UTC, koenderks commented
I think this still needs the error handing for metric="eo", right?

2025-02-04 15:40 UTC, koenderks commented
This seems like a lot of empty space, can you put the legend closer to the diagram? Also, revert the changes in the `stanmodels.R` file and don't forget to implement error handling for `metric = "eo"` in `model_fairness()`

![image](https://github.com/user-attachments/assets/636eda00-783a-4675-8cbf-d2502c7fc729)

2025-02-06 09:14 UTC, federicapicogna commented
The strange thing about stanmodels is that when I run the lint test, it tells me that I have to change it this way or the test will fail. As for the rest, I fixed the legend and I'm now working on "eo". 
<img width="706" alt="Screenshot 2025-02-06 at 10 13 52" src="https://github.com/user-attachments/assets/7403eb16-ef03-49d6-b6fa-d494cd593f05" />

2025-02-07 20:35 UTC, koenderks commented
Just implement a simple error message for when metric is "eo", we can handle the rest in JASP. Then undo all changes in stanmodels.R

2025-02-07 20:35 UTC, koenderks requested changes
See comment above

2025-02-10 13:35 UTC, koenderks requested changes
There are lots of changes in the `model_fairness.R` file, but you only need to add an error message. Please make sure that the changes here are minimal.

2025-02-10 13:35 UTC, koenderks commented on R/model_fairness.R
> +  } else {
Remove the `else` here, you quit the analysis at this point anyway if metric = "eo"

2025-02-11 08:33 UTC, merged